spring.application.name=landslide-backend

# Import local secrets (ignored by Git)
spring.config.import=optional:classpath:application-local.properties

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/landslide_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:sancheti1234}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080
